[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flux-pipeline"
version = "0.1.0"
dependencies = [
    "diffusers",
    "torch",
    "torchvision", 
    "transformers",
    "accelerate",
    "sentencepiece",
    "protobuf"
]
